### ISSUE TITLE
Missing npm package azuremaps-maplibre-gl

### ISSUE THREAD

**Issue by fuliii1** [Azure-Samples/AzureMapsCodeSamples#116]
Hi Team,

I use azure-maps-control from my Angular spa. After I upgraded azure-maps-control to 3.0.1 my spa stopped to compile. 
The error log is the following:
```
Error: node_modules/azure-maps-control/typings/index.d.ts:2:129 - error TS2307: Cannot find module 'azuremaps-maplibre-gl' or its corresponding type declarations.

2 import { DataDrivenPropertyValueSpecification, PropertyValueSpecification, ExpressionFilterSpecification, PositionAnchor } from "azuremaps-maplibre-gl";
                                                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/azure-maps-control/typings/index.d.ts:2100:51 - error TS2304: Cannot find name 'ElevationTileSource'.

2100         enableElevation(elevationSource: string | ElevationTileSource, exaggeration?: number): void;
                                                       ~~~~~~~~~~~~~~~~~~~


Error: node_modules/azure-maps-control/typings/index.d.ts:4059:49 - error TS1246: An interface property cannot have an initializer.

4059         clusterMinPoints?: number | undefined = 2;
                                                     ~


Error: node_modules/azure-maps-control/typings/index.d.ts:4063:44 - error TS1246: An interface property cannot have an initializer.

4063         generateId?: boolean | undefined = false;
                                                ~~~~~


Error: node_modules/azure-maps-control/typings/index.d.ts:4067:70 - error TS1246: An interface property cannot have an initializer.

4067         promoteId?: { [key: string]: string } | string | undefined = undefined;
                                                                          ~~~~~~~~~


Error: node_modules/azure-maps-control/typings/index.d.ts:4071:24 - error TS1246: An interface property cannot have an initializer.

4071         filter?: any = undefined
                            ~~~~~~~~~


Error: src/app/ui/radar-map/radar-map.component.ts:207:68 - error TS2345: Argument of type 'import("D:/CODE/.NET/CSharp/2022/HailPrevention/HailPrevention/ClientApp/node_modules/azure-maps-control/typings/index").Map' is not assignable to parameter of type 'import("D:/CODE/.NET/CSharp/2022/HailPrevention/HailPrevention/ClientApp/node_modules/azure-maps-drawing-tools/node_modules/azure-maps-control/typings/index").Map'.
  Types have separate declarations of a private property 'styleLayerIds'.

207     this._drawingManager = new atlasdrawing.drawing.DrawingManager(this._map, {});
                                                                       ~~~~~~~~~


Error: src/app/ui/radar-map/radar-map.component.ts:210:26 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '"drawingchanging"' is not assignable to parameter of type '"sourceadded" | "sourceremoved"'.

210     this._map.events.add('drawingchanging', this._drawingManager, (shape) => this.measureShape(shape));
                             ~~~~~~~~~~~~~~~~~

  node_modules/azure-maps-control/typings/index.d.ts:5105:9
    5105         add(eventType: "sourceadded" | "sourceremoved", target: atlas.source.Source | atlas.source.Source[], callback: (e: atlas.source.Source) => void): void;
                 ~~~
    The last overload is declared here.
```

For me seems that the root cause is that the azuremaps-maplibre-gl is an unknown npm package.

This is package is a dev dependency of azure-maps-control.

Thanks,
Gabor Fulop

**Comment by cschotte** [comment]
A fix is being developed and will be available in the upcoming release. To address the problem now, you may alternatively add `skipLibCheck: true` to the tsconfig files to bypass the error.

**Comment by fuliii1** [comment]
Hi @cschotte,

Thanks for your help. Your workaround works because the most of compilation errors disappeared but not all of them.
I'm using DrawingManager from azure-maps-drawing-tools npm.
If I upgrade the to azure-maps-control 3.0.1 I get the following compilation issues:

`Error: src/app/ui/radar-map/radar-map.component.ts:208:68 - error TS2345: Argument of type 'import("D:/CODE/.NET/CSharp/2022/HailPrevention/HailPrevention/ClientApp/node_modules/azure-maps-control/typings/index").Map' is not assignable to parameter of type 'import("D:/CODE/.NET/CSharp/2022/HailPrevention/HailPrevention/ClientApp/node_modules/azure-maps-drawing-tools/node_modules/azure-maps-control/typings/index").Map'.
  Types have separate declarations of a private property 'styleLayerIds'.

208     this._drawingManager = new atlasdrawing.drawing.DrawingManager(this._map, {});
                                                                       ~~~~~~~~~


Error: src/app/ui/radar-map/radar-map.component.ts:211:26 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '"drawingchanging"' is not assignable to parameter of type '"sourceadded" | "sourceremoved"'.

211     this._map.events.add('drawingchanging', this._drawingManager, (shape) => this.measureShape(shape));
                             ~~~~~~~~~~~~~~~~~

  node_modules/azure-maps-control/typings/index.d.ts:5143:9
    5143         add(eventType: "sourceadded" | "sourceremoved", target: atlas.source.Source | atlas.source.Source[], callback: (e: atlas.source.Source) => void): void;
                 ~~~
    The last overload is declared here.
`
I'm unsig the 1.0.0 version of azure-maps-drawing-tools. As I know curently this is the newest. 

Thanks for your help,
Gabor Fulop

**Comment by cschotte** [comment]
The issue is caused by azure-maps-drawing-tools resolving to a different version of azure-maps-control, thus raising an inconsistency in typing. 

We'll have a fix available for azure-maps-drawing-tools@1.0.1 for the next release.

Meanwhile, you can add //@ts-ignore in front of the lines with errors to bypass them.

**Comment by fuliii1** [comment]
Hi @cschotte,

The suggested workarounds works.

Thanks for your support,
Gabor Fulop
